### ISSUE TITLE
Undefined variables 1.20 - unique_total - etc.

### ISSUE THREAD

**Issue by ShaiMagal** [telartis/awstatstotals#1]
Hi.

after update from 1.19 to 1.20 we see php warnings.
So, no totals at bottom of page for all vhosts are shown.

**We changed local variables for example ($unique_total) to ($this->unique_total) and it is working now.**

Lines:
139-146 + 163-173 + 570-580

Warning: Undefined variable $unique_total in /xxx/awstatstotals.class.php on line 569

Warning: Undefined variable $visits_total in /xxx/awstatstotals.class.php on line 570

Warning: Undefined variable $pages_total in /xxx/awstatstotals.class.php on line 571

Warning: Undefined variable $hits_total in /xxx/awstatstotals.class.php on line 572

Warning: Undefined variable $bandwidth_total in /xxx/awstatstotals.class.php on line 573

**Comment by telartis** [comment]
Hi Dominik,

I just fixed this it, so the totals are visible again.

Jeroen

**Comment by ShaiMagal** [comment]
Uhm, good, I was eager :)
