### ISSUE TITLE
Installation instruction

### ISSUE THREAD

**Issue by miszterx** [telartis/awstatstotals#2]
Hi,

I use the 1.81 version of the awstatstotal. I just loaded the awstatstotal.php before, and it gave back the HTML page with the available stats.
I can see you redesigned the current awstatstotal, but unfortunately I am lack of PHP knowledge, and I cannot make it working.
I have updated the awstatstotal.php file DirData, AWStatsURL, DirLang. But I cannot directly call the PHP to present the awstats as before.

I can see in the embedded instructions I need to create a new file and refer it, but I couldn't make. :(

Can you help me how I can make it work? I have the folder, where the awstatstotals.php and awstats.php are located and it is available from the webserver.

**Comment by telartis** [comment]
Hi miszterx,

If you want to use the same awstatstotal.php file, without creating a new file, you could add the following two lines right after the namespace:

`$obj = new awstatstotals();`
`$obj->main();`

Your setup will work exactly the same as before.

Cheers, Jeroen
